meta_product_name: "Signary"

meta_title: "Signary - Bridging Worlds Through Sign Language"

meta_description: "An application that allows you to build your own selection of sign language videos and get closer to deaf people"

meta_image: "cover.jpg" # should exist in `app/assets/images/`
